### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by TyrionChou** [weiyuk/fluent-cap#1]
您好，我想咨询一下您在《标签增强的中文看图造句》一文中使用的数据库是否就是https://github.com/li-xirong/cross-lingual-cap中的flickr8k-cn与flickr30k-cn，我使用了此数据库做了基于tensorflow  baseline NIC模型的实验，但效果与论文中的效果相差甚远，如果是使用的相同的数据库，能否将训练超参数分享一下呢？万分感谢！

**Comment by weiyuk** [comment]
Hi. 这里使用的数据就是在这个[链接](https://github.com/li-xirong/cross-lingual-cap) 中的数据。
在[这里](https://github.com/weiyuk/fluent-cap/blob/master/model_conf/8k_neuraltalk.py)有训练模型使用的参数。谢谢~
