### ISSUE TITLE
运行结果有些疑问

### ISSUE THREAD

**Issue by terima-tang** [weiyuk/fluent-cap#2]
你好，感谢代码分享很赞，我运行了您的程序，但是结果文件夹中并没有图中标注的路径和相应txt文件
![Inkedcap-xiu_LI](https://user-images.githubusercontent.com/22870124/55770059-8cd72080-5ab5-11e9-9709-b5cfd8c81d5d.jpg)

**Comment by weiyuk** [comment]
Hi terima, 你是运行的do-all.sh这个脚本吗？
截图中输出的最后一行就是预测句子结果文件的路径以及它的评价指标得分。这个路径是通过do-all.sh中的find命令找到的结果文件，应该就在这个文件夹下：$HOME/VisualSearch/$collection/；或者你指定的rootpath目录下。

**Comment by terima-tang** [comment]
![qq](https://user-images.githubusercontent.com/22870124/55807556-fdf9f080-5b14-11e9-9c60-a9c25aac15fb.PNG)
你好，找到上面了文件了，感谢，想问下图中标的值是什么意思

**Comment by weiyuk** [comment]
可以理解为caption model给出的当前这个预测句子的score，具体的就是在预测句子时，整个句子的单词的logprob（softmax结果取对数）的求和
